//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenturaITC.DSMSystem.DAL.Model
{
    using MODEL.Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class dsmsEntities : DbContext
    {
        public dsmsEntities()
            : base("name=dsmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academic_level> academic_level { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<db_data_status> db_data_status { get; set; }
        public virtual DbSet<document_type> document_type { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<id_issuance_place> id_issuance_place { get; set; }
        public virtual DbSet<marital_status> marital_status { get; set; }
        public virtual DbSet<parameterization> parameterizations { get; set; }
        public virtual DbSet<parameterization_bool> parameterization_bool { get; set; }
        public virtual DbSet<payment_installment> payment_installment { get; set; }
        public virtual DbSet<payment_status> payment_status { get; set; }
        public virtual DbSet<payment_type> payment_type { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<student_documentation> student_documentation { get; set; }
        public virtual DbSet<student_enrollment> student_enrollment { get; set; }
        public virtual DbSet<student_payment> student_payment { get; set; }
        public virtual DbSet<student_type> student_type { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
    }
}
