//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenturaITC.DSMSystem.MODEL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_enrollment
    {
        public int id { get; set; }
        public int student_number { get; set; }
        public string category { get; set; }
        public System.DateTime enrollment_date { get; set; }
        public string enrollment_user { get; set; }
    
        public virtual student student { get; set; }
        public virtual user user { get; set; }
    }
}
